[33md44d3fb[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m)[m Remove exposed API keys and secrets
.env
[33m89a9d73[m Initial commit: SMART-JOB-AGENT with resume parsing and job discovery
.env
data/Tumulavakarteek_resume.pdf
jobs.json
profile.json
src/__pycache__/config.cpython-312.pyc
src/__pycache__/job_discovery.cpython-312.pyc
src/__pycache__/main.cpython-312.pyc
src/__pycache__/resume_parser.cpython-312.pyc
src/config.py
src/job_discovery.py
src/main.py
[33m22e2623[m handling multiple resumes
.env
.gitignore
profile.json
src/__pycache__/main.cpython-312.pyc
src/__pycache__/resume_parser.cpython-312.pyc
src/main.py
src/resume_parser.py
[33m34e50dc[m[33m ([m[1;31morigin/main[m[33m)[m Remove secrets and add .gitignore
.env
.gitignore
[33md960c6f[m Job Roles Finder Done!
.env
README.md
data/kiruba 7th sem resume.pdf
profile.json
requirements.txt
src/__init__.py
src/__pycache__/__init__.cpython-312.pyc
src/__pycache__/config.cpython-312.pyc
src/__pycache__/main.cpython-312.pyc
src/__pycache__/resume_parser.cpython-312.pyc
src/config.py
src/main.py
src/resume_parser.py
test.txt
venv/Lib/site-packages/certifi-2025.8.3.dist-info/INSTALLER
venv/Lib/site-packages/certifi-2025.8.3.dist-info/METADATA
venv/Lib/site-packages/certifi-2025.8.3.dist-info/RECORD
venv/Lib/site-packages/certifi-2025.8.3.dist-info/WHEEL
venv/Lib/site-packages/certifi-2025.8.3.dist-info/licenses/LICENSE
venv/Lib/site-packages/certifi-2025.8.3.dist-info/top_level.txt
venv/Lib/site-packages/certifi/__init__.py
venv/Lib/site-packages/certifi/__main__.py
venv/Lib/site-packages/certifi/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/certifi/__pycache__/__main__.cpython-312.pyc
venv/Lib/site-packages/certifi/__pycache__/core.cpython-312.pyc
venv/Lib/site-packages/certifi/cacert.pem
venv/Lib/site-packages/certifi/core.py
venv/Lib/site-packages/certifi/py.typed
venv/Lib/site-packages/charset_normalizer-3.4.3.dist-info/INSTALLER
venv/Lib/site-packages/charset_normalizer-3.4.3.dist-info/METADATA
venv/Lib/site-packages/charset_normalizer-3.4.3.dist-info/RECORD
venv/Lib/site-packages/charset_normalizer-3.4.3.dist-info/WHEEL
venv/Lib/site-packages/charset_normalizer-3.4.3.dist-info/entry_points.txt
venv/Lib/site-packages/charset_normalizer-3.4.3.dist-info/licenses/LICENSE
venv/Lib/site-packages/charset_normalizer-3.4.3.dist-info/top_level.txt
venv/Lib/site-packages/charset_normalizer/__init__.py
venv/Lib/site-packages/charset_normalizer/__main__.py
venv/Lib/site-packages/charset_normalizer/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/__main__.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/api.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/cd.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/constant.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/legacy.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/md.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/models.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/utils.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/__pycache__/version.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/api.py
venv/Lib/site-packages/charset_normalizer/cd.py
venv/Lib/site-packages/charset_normalizer/cli/__init__.py
venv/Lib/site-packages/charset_normalizer/cli/__main__.py
venv/Lib/site-packages/charset_normalizer/cli/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/cli/__pycache__/__main__.cpython-312.pyc
venv/Lib/site-packages/charset_normalizer/constant.py
venv/Lib/site-packages/charset_normalizer/legacy.py
venv/Lib/site-packages/charset_normalizer/md.cp312-win_amd64.pyd
venv/Lib/site-packages/charset_normalizer/md.py
venv/Lib/site-packages/charset_normalizer/md__mypyc.cp312-win_amd64.pyd
venv/Lib/site-packages/charset_normalizer/models.py
venv/Lib/site-packages/charset_normalizer/py.typed
venv/Lib/site-packages/charset_normalizer/utils.py
venv/Lib/site-packages/charset_normalizer/version.py
venv/Lib/site-packages/dotenv/__init__.py
venv/Lib/site-packages/dotenv/__main__.py
venv/Lib/site-packages/dotenv/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/dotenv/__pycache__/__main__.cpython-312.pyc
venv/Lib/site-packages/dotenv/__pycache__/cli.cpython-312.pyc
venv/Lib/site-packages/dotenv/__pycache__/ipython.cpython-312.pyc
venv/Lib/site-packages/dotenv/__pycache__/main.cpython-312.pyc
venv/Lib/site-packages/dotenv/__pycache__/parser.cpython-312.pyc
venv/Lib/site-packages/dotenv/__pycache__/variables.cpython-312.pyc
venv/Lib/site-packages/dotenv/__pycache__/version.cpython-312.pyc
venv/Lib/site-packages/dotenv/cli.py
venv/Lib/site-packages/dotenv/ipython.py
venv/Lib/site-packages/dotenv/main.py
venv/Lib/site-packages/dotenv/parser.py
venv/Lib/site-packages/dotenv/py.typed
venv/Lib/site-packages/dotenv/variables.py
venv/Lib/site-packages/dotenv/version.py
venv/Lib/site-packages/fitz/__init__.py
venv/Lib/site-packages/fitz/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/fitz/__pycache__/table.cpython-312.pyc
venv/Lib/site-packages/fitz/__pycache__/utils.cpython-312.pyc
venv/Lib/site-packages/fitz/table.py
venv/Lib/site-packages/fitz/utils.py
venv/Lib/site-packages/idna-3.10.dist-info/INSTALLER
venv/Lib/site-packages/idna-3.10.dist-info/LICENSE.md
venv/Lib/site-packages/idna-3.10.dist-info/METADATA
venv/Lib/site-packages/idna-3.10.dist-info/RECORD
venv/Lib/site-packages/idna-3.10.dist-info/WHEEL
venv/Lib/site-packages/idna/__init__.py
venv/Lib/site-packages/idna/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/idna/__pycache__/codec.cpython-312.pyc
venv/Lib/site-packages/idna/__pycache__/compat.cpython-312.pyc
venv/Lib/site-packages/idna/__pycache__/core.cpython-312.pyc
venv/Lib/site-packages/idna/__pycache__/idnadata.cpython-312.pyc
venv/Lib/site-packages/idna/__pycache__/intranges.cpython-312.pyc
venv/Lib/site-packages/idna/__pycache__/package_data.cpython-312.pyc
venv/Lib/site-packages/idna/__pycache__/uts46data.cpython-312.pyc
venv/Lib/site-packages/idna/codec.py
venv/Lib/site-packages/idna/compat.py
venv/Lib/site-packages/idna/core.py
venv/Lib/site-packages/idna/idnadata.py
venv/Lib/site-packages/idna/intranges.py
venv/Lib/site-packages/idna/package_data.py
venv/Lib/site-packages/idna/py.typed
venv/Lib/site-packages/idna/uts46data.py
venv/Lib/site-packages/pip-25.0.1.dist-info/AUTHORS.txt
venv/Lib/site-packages/pip-25.0.1.dist-info/INSTALLER
venv/Lib/site-packages/pip-25.0.1.dist-info/LICENSE.txt
venv/Lib/site-packages/pip-25.0.1.dist-info/METADATA
venv/Lib/site-packages/pip-25.0.1.dist-info/RECORD
venv/Lib/site-packages/pip-25.0.1.dist-info/REQUESTED
venv/Lib/site-packages/pip-25.0.1.dist-info/WHEEL
venv/Lib/site-packages/pip-25.0.1.dist-info/entry_points.txt
venv/Lib/site-packages/pip-25.0.1.dist-info/top_level.txt
venv/Lib/site-packages/pip/__init__.py
venv/Lib/site-packages/pip/__main__.py
venv/Lib/site-packages/pip/__pip-runner__.py
venv/Lib/site-packages/pip/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/__pycache__/__main__.cpython-312.pyc
venv/Lib/site-packages/pip/__pycache__/__pip-runner__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__init__.py
venv/Lib/site-packages/pip/_internal/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__pycache__/build_env.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__pycache__/cache.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__pycache__/configuration.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__pycache__/exceptions.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__pycache__/main.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__pycache__/pyproject.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__pycache__/self_outdated_check.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/__pycache__/wheel_builder.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/build_env.py
venv/Lib/site-packages/pip/_internal/cache.py
venv/Lib/site-packages/pip/_internal/cli/__init__.py
venv/Lib/site-packages/pip/_internal/cli/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/autocompletion.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/base_command.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/cmdoptions.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/command_context.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/index_command.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/main.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/main_parser.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/parser.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/progress_bars.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/req_command.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/spinners.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/__pycache__/status_codes.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/cli/autocompletion.py
venv/Lib/site-packages/pip/_internal/cli/base_command.py
venv/Lib/site-packages/pip/_internal/cli/cmdoptions.py
venv/Lib/site-packages/pip/_internal/cli/command_context.py
venv/Lib/site-packages/pip/_internal/cli/index_command.py
venv/Lib/site-packages/pip/_internal/cli/main.py
venv/Lib/site-packages/pip/_internal/cli/main_parser.py
venv/Lib/site-packages/pip/_internal/cli/parser.py
venv/Lib/site-packages/pip/_internal/cli/progress_bars.py
venv/Lib/site-packages/pip/_internal/cli/req_command.py
venv/Lib/site-packages/pip/_internal/cli/spinners.py
venv/Lib/site-packages/pip/_internal/cli/status_codes.py
venv/Lib/site-packages/pip/_internal/commands/__init__.py
venv/Lib/site-packages/pip/_internal/commands/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/cache.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/check.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/completion.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/configuration.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/debug.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/download.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/freeze.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/hash.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/help.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/index.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/inspect.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/install.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/list.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/search.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/show.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/uninstall.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/__pycache__/wheel.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/commands/cache.py
venv/Lib/site-packages/pip/_internal/commands/check.py
venv/Lib/site-packages/pip/_internal/commands/completion.py
venv/Lib/site-packages/pip/_internal/commands/configuration.py
venv/Lib/site-packages/pip/_internal/commands/debug.py
venv/Lib/site-packages/pip/_internal/commands/download.py
venv/Lib/site-packages/pip/_internal/commands/freeze.py
venv/Lib/site-packages/pip/_internal/commands/hash.py
venv/Lib/site-packages/pip/_internal/commands/help.py
venv/Lib/site-packages/pip/_internal/commands/index.py
venv/Lib/site-packages/pip/_internal/commands/inspect.py
venv/Lib/site-packages/pip/_internal/commands/install.py
venv/Lib/site-packages/pip/_internal/commands/list.py
venv/Lib/site-packages/pip/_internal/commands/search.py
venv/Lib/site-packages/pip/_internal/commands/show.py
venv/Lib/site-packages/pip/_internal/commands/uninstall.py
venv/Lib/site-packages/pip/_internal/commands/wheel.py
venv/Lib/site-packages/pip/_internal/configuration.py
venv/Lib/site-packages/pip/_internal/distributions/__init__.py
venv/Lib/site-packages/pip/_internal/distributions/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/distributions/__pycache__/base.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/distributions/__pycache__/installed.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/distributions/__pycache__/sdist.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/distributions/__pycache__/wheel.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/distributions/base.py
venv/Lib/site-packages/pip/_internal/distributions/installed.py
venv/Lib/site-packages/pip/_internal/distributions/sdist.py
venv/Lib/site-packages/pip/_internal/distributions/wheel.py
venv/Lib/site-packages/pip/_internal/exceptions.py
venv/Lib/site-packages/pip/_internal/index/__init__.py
venv/Lib/site-packages/pip/_internal/index/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/index/__pycache__/collector.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/index/__pycache__/package_finder.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/index/__pycache__/sources.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/index/collector.py
venv/Lib/site-packages/pip/_internal/index/package_finder.py
venv/Lib/site-packages/pip/_internal/index/sources.py
venv/Lib/site-packages/pip/_internal/locations/__init__.py
venv/Lib/site-packages/pip/_internal/locations/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/locations/__pycache__/_distutils.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/locations/__pycache__/_sysconfig.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/locations/__pycache__/base.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/locations/_distutils.py
venv/Lib/site-packages/pip/_internal/locations/_sysconfig.py
venv/Lib/site-packages/pip/_internal/locations/base.py
venv/Lib/site-packages/pip/_internal/main.py
venv/Lib/site-packages/pip/_internal/metadata/__init__.py
venv/Lib/site-packages/pip/_internal/metadata/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/metadata/__pycache__/_json.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/metadata/__pycache__/base.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/metadata/__pycache__/pkg_resources.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/metadata/_json.py
venv/Lib/site-packages/pip/_internal/metadata/base.py
venv/Lib/site-packages/pip/_internal/metadata/importlib/__init__.py
venv/Lib/site-packages/pip/_internal/metadata/importlib/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/metadata/importlib/__pycache__/_compat.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/metadata/importlib/__pycache__/_dists.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/metadata/importlib/__pycache__/_envs.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/metadata/importlib/_compat.py
venv/Lib/site-packages/pip/_internal/metadata/importlib/_dists.py
venv/Lib/site-packages/pip/_internal/metadata/importlib/_envs.py
venv/Lib/site-packages/pip/_internal/metadata/pkg_resources.py
venv/Lib/site-packages/pip/_internal/models/__init__.py
venv/Lib/site-packages/pip/_internal/models/__pycache__/__init__.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/candidate.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/direct_url.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/format_control.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/index.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/installation_report.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/link.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/scheme.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/search_scope.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/selection_prefs.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/target_python.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/__pycache__/wheel.cpython-312.pyc
venv/Lib/site-packages/pip/_internal/models/candidate.py
venv/Lib/site-packages/pip/_internal/models/direct_url.py
venv/Lib/site-packages/pip/_internal/models/format_control.py
venv/Lib/site-packages/pip/_internal/models/index.py
venv/Lib/site-packages/pip/_internal/models/installation_report.py
venv/Lib/site-packages/pip/_internal/models/link.py
venv/Lib/site-packages/pip/_internal/models/scheme.py
venv/Lib/site-packages/pip/_internal/models/search_scope.py
venv/Lib/site-packages/pip/_internal/models/selection_prefs.py
venv/Lib/site-packages/pip/_internal